AWSTemplateFormatVersion: 2010-09-09

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ItemTable: !Ref ItemTable
        UserTable: !Ref UserTable
      TemplateURL: api/cloudformation.yml

  ItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: item_tag
        KeyType: HASH
      AttributeDefinitions:
        - AttributeName: item_tag
          AttributeType: S

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
    