version: '3.7'

services:
    database:
        build:
            context: .
            target: database
            args:
                - DB_USER=database
                - DB_PASS=database
                - DB_NAME=database
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    core_deployment:
        build:
            context: .
            target: deployment

    core_development:
        build:
            context: .
            target: development
        volumes:
            - ./api:/var/app/api
            - ./migrations:/var/app/migrations
        environment:
            - DATABASE_URL=postgres://database:database@database:5432/database

networks:
  found_your_stuff_core:
    name: found_your_stuff_core
