openapi: 3.0.1

info:
  title: FoundYourStuff
  version: ""

paths:
  /users:
    get:
      description: if user marked public, returns the users contact info
      operationId: handlers.getUserByExternalID
      parameters:
        - name: external_id
          in: query
          schema:
            type: string
      responses:
        "200": 
          description: 200 ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  phone:
                    type: string
                  email: 
                    type: string
                    format: email
        "404":
          description: A user with the specified ID was not found.
    post:
      description: create new user
      operationId: handlers.createNewUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200": 
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  # /users/{userId}:
  #   get:
  #     description: get user by GUID
  #     operationId: item_tracker_core.handlers.getUserById
  #     parameters:
  #       - name: userId
  #         in: path
  #         description: GUID of user to update
  #         required: true
  #         schema:
  #           type: string
  #           format: GUID
  #     responses:
  #       "200": 
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/User'
              

  #   patch:
  #     description: update existing user
  #     operationId: item_tracker_core.handlers.updateUserById
  #     parameters:
  #       - name: userId
  #         in: path
  #         description: GUID of user to update
  #         required: true
  #         schema:
  #           type: string
  #           format: GUID
  #     requestBody:
  #       required: true
  #       content:
  #         application'json:
  #           schema:
  #             $ref: '#/components/schemas/User'
  #     responses:
  #       "200": 
  #         description: Updated


      
  # /tag:
  #   post:
  #     description: Adds tag associated to logged in user
  #     operationId: item_tracker_core.handlers.add_tag
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               item_name:
  #                 type: string
  #               item_desc:
  #                 type: string
  #     responses:
  #       "200":
  #         description: 200 ok
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               properties:
  #                 item_id:
  #                   type: string


components:
  schemas:
    User:
      type: object
      required:
        - email
        - password
        - name
        - phone_number
        - contact
        - active
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        name:
          type: string
        phone_number:
          type: string
        contact:
          type: boolean
        active: 
          type: boolean
    Tag:
      type: object
      required:
        - user_id
        - name
        - active
      properties:
        user_id:
          type: string
        name:
          type: string
        picture:
          type: string
        active:
          type: boolean
    Message:
      type: object
      required:
        - tag_id
        - time_stamp
        - body
        - read
      properties:
        tag_id:
          type: string
        time_stamp:
          type: string
        body:
          type: string
        picture:
          type: string
        read:
          type: boolean

      
      