name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2
  TEMPLATE_BUCKET: fyt-lambda-templates

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dependancies
        run: |
          pip install --upgrade pip
          pip install -r api/requirements.txt -t api/src
      - name: Package and deploy
        run: |
          aws cloudformation package \
            --template-file cloudformation.yml \
            --s3-bucket ${TEMPLATE_BUCKET} \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name FYT \
            --template-file packaged.yml \
            --capabilities CAPABILITY_IAM \
